version: '3'
services:
  mongodb:
    image: alexpunct/mongo:3.4
    volumes:
      - loopback-mongo-data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGODB_ADMIN_USER: 'admin'
      MONGODB_ADMIN_PASS: 'admin_password'
      MONGODB_APPLICATION_DATABASE: 'loopback'
      MONGODB_APPLICATION_USER: 'scott'
      MONGODB_APPLICATION_PASS: 'tiger'
volumes:
  loopback-mongo-data:
